#include "AiObjectContext.h"
#include "TriggerContext.h"
#include "ChatTriggerContext.h"
#include "WorldPacketTriggerContext.h"
#include "Ai/Raid/Aq20/RaidAq20TriggerContext.h"
#include "Ai/Raid/MoltenCore/RaidMcTriggerContext.h"
#include "Ai/Raid/BlackwingLair/RaidBwlTriggerContext.h"
#include "Ai/Raid/Karazhan/RaidKarazhanTriggerContext.h"
#include "Ai/Raid/GruulsLair/RaidGruulsLairTriggerContext.h"
#include "Ai/Raid/Magtheridon/RaidMagtheridonTriggerContext.h"
#include "Ai/Raid/Naxxramas/RaidNaxxTriggerContext.h"
#include "Ai/Raid/SerpentshrineCavern/RaidSSCTriggerContext.h"
#include "Ai/Raid/TempestKeep/RaidTempestKeepTriggerContext.h"
#include "Ai/Raid/ZulAman/RaidZulAmanTriggerContext.h"
#include "Ai/Raid/ObsidianSanctum/RaidOsTriggerContext.h"
#include "Ai/Raid/EyeOfEternity/RaidEoETriggerContext.h"
#include "Ai/Raid/VaultOfArchavon/RaidVoATriggerContext.h"
#include "Ai/Raid/Ulduar/RaidUlduarTriggerContext.h"
#include "Ai/Raid/Onyxia/RaidOnyxiaTriggerContext.h"
#include "Ai/Raid/Icecrown/RaidIccTriggerContext.h"
#include "Ai/Dungeon/WotlkDungeonTriggerContext.h"
#include "../../../strategy/raids/blacktemple/BlackTempleTriggerContext.h"
#include "../../../strategy/raids/serpentshrine/SerpentshrineTriggerContext.h"
#include "../../../strategy/raids/tempestkeep/TempestKeepTriggerContext.h"
#include "../../../strategy/dungeons/tbc/sethekkhalls/SethekkHallsTriggerContext.h"
#include "../../../strategy/dungeons/tbc/auchenaicrypts/AuchenaiCryptsTriggerContext.h"
#include "../../../strategy/dungeons/tbc/blackmorass/BlackMorassTriggerContext.h"
#include "../../../strategy/dungeons/tbc/escapefromdurnholde/EscapeFromDurnholdeTriggerContext.h"
#include "../../../strategy/dungeons/tbc/magistersterrace/MagistersTerraceTriggerContext.h"
#include "../../../strategy/dungeons/tbc/steamvault/SteamvaultTriggerContext.h"
#include "../../../strategy/dungeons/tbc/hellfireramparts/HellfireRampartsTriggerContext.h"
#include "../../../strategy/dungeons/tbc/bloodfurnace/BloodFurnaceTriggerContext.h"
#include "../../../strategy/dungeons/tbc/slavepens/SlavePensTriggerContext.h"
#include "../../../strategy/dungeons/tbc/underbog/UnderbogTriggerContext.h"
#include "../../../strategy/dungeons/tbc/manatombs/ManaTombsTriggerContext.h"
#include "../../../strategy/dungeons/tbc/shatteredhalls/ShatteredHallsTriggerContext.h"
#include "../../../strategy/dungeons/tbc/shadowlabyrinth/ShadowLabyrinthTriggerContext.h"
#include "../../../strategy/dungeons/tbc/arcatraz/ArcatrazTriggerContext.h"
#include "../../../strategy/dungeons/tbc/botanica/BotanicaTriggerContext.h"
#include "../../../strategy/dungeons/tbc/mechanar/MechanarTriggerContext.h"

void AiObjectContext::BuildSharedTriggerContexts(SharedNamedObjectContextList<Trigger>& triggerContexts)
{
    triggerContexts.Add(new TriggerContext());
    triggerContexts.Add(new ChatTriggerContext());
    triggerContexts.Add(new WorldPacketTriggerContext());
    triggerContexts.Add(new RaidAq20TriggerContext());
    triggerContexts.Add(new RaidMcTriggerContext());
    triggerContexts.Add(new RaidBwlTriggerContext());
    triggerContexts.Add(new RaidKarazhanTriggerContext());
    triggerContexts.Add(new RaidGruulsLairTriggerContext());
    triggerContexts.Add(new RaidMagtheridonTriggerContext());
    triggerContexts.Add(new RaidNaxxTriggerContext());
    triggerContexts.Add(new RaidSSCTriggerContext());
    triggerContexts.Add(new RaidTempestKeepTriggerContext());
    triggerContexts.Add(new RaidZulAmanTriggerContext());
    triggerContexts.Add(new RaidOsTriggerContext());
    triggerContexts.Add(new RaidEoETriggerContext());
    triggerContexts.Add(new RaidVoATriggerContext());
    triggerContexts.Add(new RaidUlduarTriggerContext());
    triggerContexts.Add(new RaidOnyxiaTriggerContext());
    triggerContexts.Add(new RaidIccTriggerContext());
    triggerContexts.Add(new WotlkDungeonUKTriggerContext());
    triggerContexts.Add(new WotlkDungeonNexTriggerContext());
    triggerContexts.Add(new WotlkDungeonANTriggerContext());
    triggerContexts.Add(new WotlkDungeonOKTriggerContext());
    triggerContexts.Add(new WotlkDungeonDTKTriggerContext());
    triggerContexts.Add(new WotlkDungeonVHTriggerContext());
    triggerContexts.Add(new WotlkDungeonGDTriggerContext());
    triggerContexts.Add(new WotlkDungeonHoSTriggerContext());
    triggerContexts.Add(new WotlkDungeonHoLTriggerContext());
    triggerContexts.Add(new WotlkDungeonOccTriggerContext());
    triggerContexts.Add(new WotlkDungeonUPTriggerContext());
    triggerContexts.Add(new WotlkDungeonCoSTriggerContext());
    triggerContexts.Add(new WotlkDungeonFoSTriggerContext());
    triggerContexts.Add(new WotlkDungeonPoSTriggerContext());
    triggerContexts.Add(new WotlkDungeonToCTriggerContext());

    // Custom
    triggerContexts.Add(new RaidBtTriggerContext());
    triggerContexts.Add(new SerpentshrineTriggerContext());
    triggerContexts.Add(new TempestKeepTriggerContext());
    triggerContexts.Add(new EscapeFromDurnholdeTriggerContext());
    triggerContexts.Add(new TbcDungeonSHTriggerContext());
    triggerContexts.Add(new TbcDungeonACTriggerContext());
    triggerContexts.Add(new BlackMorassTriggerContext());
    triggerContexts.Add(new MagistersTerraceTriggerContext());
    triggerContexts.Add(new SteamvaultTriggerContext());
    triggerContexts.Add(new HellfireRampartsTriggerContext());
    triggerContexts.Add(new BloodFurnaceTriggerContext());
    triggerContexts.Add(new SlavePensTriggerContext());
    triggerContexts.Add(new UnderbogTriggerContext());
    triggerContexts.Add(new ManaTombsTriggerContext());
    triggerContexts.Add(new ShatteredHallsTriggerContext());
    triggerContexts.Add(new ShadowLabyrinthTriggerContext());
    triggerContexts.Add(new ArcatrazTriggerContext());
    triggerContexts.Add(new BotanicaTriggerContext());
    triggerContexts.Add(new MechanarTriggerContext());
}
